### ISSUE TITLE
[FEATURE] TCP Fast Open

### ISSUE THREAD

**Issue by zonyitoo** [shadowsocks/shadowsocks-rust#184]
TCP Fast Open is supported in [shadowsocks-libev](https://github.com/shadowsocks/shadowsocks-libev). Since it is one of the most popular shadowsocks servers implementation, it would better to be compatible with it.

## TODO

- Network Library Support
    * [ ] Mio: https://github.com/tokio-rs/mio/issues/638
    * [ ] Tokio
    * libc
        - [ ] macOS: https://github.com/rust-lang/libc/issues/1632
        - [x] Linux, already supported. But using `TCP_FASTOPEN_CONNECT` in Kernel >= 4.11 would be a lot more convenient. https://github.com/rust-lang/libc/issues/1633
        - [x] Windows. All APIs are already supported in `winapi` crate.
            * Missing `TCP_FASTOPEN` definition: https://github.com/retep998/winapi-rs/issues/856
            * Don't know how to use `ConnectEx`, fallback to `connect` temporary

**Comment by zonyitoo** [comment]
Since Mio and Tokio don't have plan on supporting TFO, I am going to write a separate crate (`mio-tfo`, `tokio-tfo` maybe).

**Comment by dev4u** [comment]
Why spend time on tfo?
As far as my experience in use, there is no perceptible improvement to the use effect.
It will also cause instability under the mobile network.

**Comment by zonyitoo** [comment]
Yup. So I have given up.

**Comment by 0x112** [comment]
@zonyitoo 请问这个特性有进展吗？

> Why spend time on tfo?
> As far as my experience in use, there is no perceptible improvement to the use effect.
> It will also cause instability under the mobile network.

我觉得还是作为一个可选项加进来比较好，因为有时候不需要用到移动网络。
当我在使用libev版本的时候，两端开启TFO时并成功生效时，会感觉快一点点，可以用这些命令可以测试TFO是否开启：
```
grep '^TcpExt:' /proc/net/netstat | cut -d ' ' -f 91-96 | column -t
grep '^TcpExt:' /proc/net/netstat | cut -d ' ' -f 90-95 | column -t
```

**Comment by database64128** [comment]
TFO is dead. This issue should be closed.

**Comment by zonyitoo** [comment]
> @zonyitoo 请问这个特性有进展吗？

Nope. I haven't spent any time on it recently. But I have already done in my local branch.

TFO requires lots of changes in API and haven't supported officially by mainstream network libraries in Rust, such as libstd, async-std, tokio, mio. It is quite nasty to make the current API to be compatible with TFO.

IMHO, TFO is dead. I don't see any massive production use case with TFO, maybe because TFO have to be supported by the OS, and it requires applications to support it explicitly by calling different APIs.

Back to this issue, I won't doubt that TFO may have benefits on connection latency, but it shouldn't be a lot that you can "feel" without having pressure tests. The performance test [in this paper](https://research.google.com/pubs/archive/37517.pdf) shows the following conclution:

>  As expected, TFO improves the PLT when the RTT is high for all the sites we tested. When the RTT is small and the network delay is only a small fraction of PLT, the resource processing time would exceed network time, so the gains from TFO are expected to be small. But even for pages heavy on content and with short emulated RTT (i.e. 20ms), TFO accelerates PLT by 4–5%. Conversely, for simpler pages such as wikipedia, the browser spends most of its time waiting for network transfers rather than processing the retrieved content, and thus TFO offers significant improvements of 16% and 41% with 100ms and 200ms RTTs respectively. The 200ms RTT figures roughly correspond to the expected performance on mobile devices since mobile RTTs are typically on the order of 100–200ms 

If TFO is good, why Google is now focusing on HTTP/3 (QUIC) instead of pushing TFO forwards? :)

**Comment by 0x112** [comment]
> So it should benefit in high RTT networks, and the network between locals and servers are usually have high RTTs. In other words, TFO may have benefits in this project.

我大概清楚了，谢谢您的解答 :)

**Comment by zonyitoo** [comment]
Any PRs are welcome.

**Comment by zonyitoo** [comment]
After a day, I am getting interested in pushing this forward. No matter it is useful or not, just for fun.

**Comment by 0x112** [comment]
> After a day, I am getting interested in pushing this forward. No matter it is useful or not, just for fun.

😅😅作为一个Optional Features怎么样？如果需要用到才在编译时加入`--features "tcp-fast-open"`会不会比较好？

（另外想请教一下，ss-rust的二进制文件比较大，能不能在编译时执行strip？我现在用了这个方法：https://github.com/rust-lang/cargo/issues/3483#issuecomment-431209957 这是正确的做法吗？）

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust/issues/276

It is 2021 now, what kind of device couldn't provide 2MB free space?

**Comment by 0x112** [comment]
> #276

谢谢 👍 

> It is 2021 now, what kind of device couldn't provide 2MB free space?

这不是空间的问题，只是想习惯性的削减一下体积

**Comment by zonyitoo** [comment]
Compile with `-s` will make generated code to be a lot slower.

**Comment by 0x112** [comment]
> Compile with `-s` will make generated code to be a lot slower.

感谢提醒哈，我原本是以为对性能无影响才想要strip的。。。
